name: Build and check

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Elm environment
        uses: JorelAli/setup-elm@v1
        with:
          # Version of Elm to use. E.g. 0.19.1
          elm-version: 0.19.1

      - name: install npm dependencies
        run: npm install

      - name: Test
        run: ./node_modules/elm-app/bin/elm-app test
